checkshttp
adevinta/vulcan-check-sdk pull request #230
Opened 2024-12-04 14:04 UTC by jesusfcr

- **Accept requests from http**
- **Add NewCheckLogFromContext func**
- **Upgrade dependencies**
- **Fix lints**
- **Improve logs**
- **Allow env variables in command exec helpers**

2024-12-05 13:26 UTC, seilagamo requested changes

2024-12-09 07:09 UTC, jesusfcr commented on bootstrapper.go
> +		if conf.Port > 0 {
Done!

2024-12-09 07:13 UTC, jesusfcr commented on config/config.go
> +	Port            int
Done!

2024-12-16 13:34 UTC, jesusfcr commented on config/config.go
> +	Port            int
Done, and set as *int as it can be empty

2024-12-17 13:19 UTC, seilagamo requested changes

2025-01-13 10:32 UTC, jesusfcr commented on go.mod
> +	github.com/aws/aws-sdk-go v1.55.5
but this is the last version at this time. No fix available.

2025-01-23 11:05 UTC, jroimartin commented on internal/http/check.go
> +}
Isn't this interface duplicated in `internal/http`, `internal/push` and `internal/local`? Why?

2025-01-23 11:15 UTC, jroimartin commented on internal/http/check.go
> +	c.server = &http.Server{Addr: fmt.Sprintf(":%d", c.port)}
The server is only used in RunAndServe. I don't think it needs to belong to the `Check` struct.

2025-01-23 11:22 UTC, jroimartin commented on internal/http/check.go
> +	http.HandleFunc("/run", c.ServeHTTP)
I'd create a new `http.ServeMux`, register the routes and assign it to the `http.Server.Handler` field.

2025-01-23 11:27 UTC, jroimartin commented on internal/http/check.go
> +		if c.shuttedDown == nil {
This seems like a race condition. I'd use an atomic. Something like:

```go
type Check struct {
	// ...

	inShutdown atomic.Bool

	// ...
}
```

and then:

```go
func (c *Check) shutingDown() bool {
	return pg.inShutdown.Load()
}
```

So you can do:

```go
if c.shutingDown() {
	// ...
}
```

I'd also check the value of the atomic at the beginning of `Check.Shutdown`. So, you can only shut the server down once. Something like,

```go
func (c *Check) Shutdown() error {
	if c.shutingDown() {
		return nil
	}
	pg.inShutdown.Store(true)

	// ...
}
```

2025-01-23 11:28 UTC, jroimartin commented on internal/http/check.go
> +	c.exitSignal <- syscall.SIGTERM
I would use different channels for the signals and the user shutdown order.

2025-01-23 11:30 UTC, jroimartin commented on internal/http/check.go
> +	c.shuttedDown = make(chan int)
I'd initialize the channel on the constructor and maybe rename it to `done` and change its type to `chan bool`.

2025-01-23 11:36 UTC, jroimartin commented on internal/http/check.go
> +		}
With the proposed changes I think this can be replaced with:

```suggestion
		c.done <- true
```

2025-01-23 11:37 UTC, jroimartin commented on internal/http/check.go
> +	s := <-c.exitSignal
I would replace with it a select that checks both the signals and user channels.

2025-01-23 11:39 UTC, jroimartin commented on internal/http/check.go
> +func (c *Check) ServeHTTP(w http.ResponseWriter, r *http.Request) {
I would not call this function `ServeHttp`. It is like `Check` implements `http.Handler` but that's not the real purpose.

2025-01-23 11:45 UTC, jesusfcr commented on .github/workflows/build.yaml
> +    runs-on: ubuntu-24.04
Agree, better use the latest, that now is the ubuntu-24.04. See https://github.com/actions/runner-images

2025-01-23 11:46 UTC, jesusfcr commented on .github/workflows/build.yaml
> +        run: go test -v ./... -count 1
sure.

2025-01-23 13:32 UTC, jesusfcr commented on internal/http/check.go
> +}
and in bootstrapper, but I only did once.

2025-01-24 08:33 UTC, jesusfcr commented on bootstrapper.go
> +			// "component":        "checks",
Updated by adding the values if available. Also I added vcs information if is available.
See https://github.com/adevinta/vulcan-check-sdk/pull/230/commits/7cacc936f22da6f217bf31370034186e72209bab

2025-01-24 09:09 UTC, jesusfcr commented on helpers/command/command.go
Not only that, IMHO they should be in an internal package inside vulcan-checks. See https://github.com/adevinta/vulcan-checks/pull/786

2025-01-24 09:46 UTC, jesusfcr commented on helpers/git.go
> +func CloneGitRepositoryContext(ctx context.Context, target string, branch string, depth int) (string, string, error) {
Ok, although is a longer name and we have a similar case in git.PlainCloneContext.

2025-01-24 09:50 UTC, jesusfcr commented on internal/http/check.go
> +func (c *Check) ServeHTTP(w http.ResponseWriter, r *http.Request) {
I need it for the Shutdown method.

2025-01-24 10:48 UTC, jesusfcr commented on internal/http/check.go
> +	c.server = &http.Server{Addr: fmt.Sprintf(":%d", c.port)}
done 877c330718594bef1468b09846b8dbdfe4e3f388

2025-01-24 10:49 UTC, jesusfcr commented on internal/http/check.go
> +	http.HandleFunc("/run", c.ServeHTTP)
done 877c330718594bef1468b09846b8dbdfe4e3f388

2025-01-24 10:49 UTC, jesusfcr commented on internal/http/check.go
> +		if c.shuttedDown == nil {
done 877c330718594bef1468b09846b8dbdfe4e3f388

2025-01-24 10:49 UTC, jesusfcr commented on internal/http/check.go
> +	c.exitSignal <- syscall.SIGTERM
done 877c330718594bef1468b09846b8dbdfe4e3f388

2025-01-24 10:49 UTC, jesusfcr commented on internal/http/check.go
> +	c.shuttedDown = make(chan int)
done 877c330718594bef1468b09846b8dbdfe4e3f388

2025-01-24 10:49 UTC, jesusfcr commented on internal/http/check.go
> +		}
done 877c330718594bef1468b09846b8dbdfe4e3f388

2025-01-24 10:49 UTC, jesusfcr commented on internal/http/check.go
> +	s := <-c.exitSignal
done 877c330718594bef1468b09846b8dbdfe4e3f388

2025-01-24 12:28 UTC, jesusfcr commented on config/config.go
> +
done

2025-01-24 12:55 UTC, jesusfcr commented on bootstrapper.go
> +	if l, ok := ctx.Value("logger").(*log.Entry); ok {
I know it's a little obscure, but I don't like the idea of having to change the signature of the public method to pass another parameter.

2025-01-27 13:56 UTC, jroimartin requested changes

2025-01-27 13:56 UTC, jroimartin commented on .github/workflows/build.yaml
> +          go test -v -count 1 ./...
Add a TODO comment explaining that, once the known race conditions are fixed, this should be changed to:

```
go test -cover -race -count 1 ./...
```

I'd also add the `-cover` flag and remove `-v`, which adds a lot of noise.

2025-01-27 13:56 UTC, jroimartin commented on config/config.go
> +	c.VcsRevision = getVcsRevision()
VCS info has nothing to do with env vars, right? It doesn't seem to belong to this function (`OverrideConfigFromEnvVars`).

2025-01-27 13:56 UTC, jroimartin commented on config/config.go
> +}
It is better to use early returns. Also, s/commin/commit/.

```suggestion
func getVcsRevision() string {
	buildInfo, ok := debug.ReadBuildInfo()
	if !ok {
		return ""
	}
		
	rev := ""
	mod := ""
	for _, s := range x.Settings {
		switch s.Key {
		case "vcs.revision":
			if len(s.Value) == 40 { // commit hash length
				rev = s.Value[:8]
			} else {
				rev = s.Value
			}
		case "vcs.modified":
			if s.Value == "true" {
				mod = "*"
			}
		}
	}
	return rev + mod
}
```

2025-01-27 13:56 UTC, jroimartin commented on config/config.go
> +				if len(s.Value) == 40 { // is the commin hash length
This check seems very weak. What are the possible values of `vcs.revision`? I'd use a regular expression here.

2025-01-27 13:56 UTC, jroimartin commented on helpers/git.go
> +func CloneGitRepositoryContext(ctx context.Context, target string, branch string, depth int) (string, string, error) {
Yeah. I also see other uses in the std library that do not follow that convention. Feel free to revert this change. If you prefer to keep it, update all the doc comments that reference this function.

2025-01-27 13:56 UTC, jroimartin commented on bootstrapper.go
> +	if l, ok := ctx.Value("logger").(*log.Entry); ok {
Fair enough. Given that this package needs a rewrite. Let's keep it like that.

2025-01-27 13:56 UTC, jroimartin commented on internal/http/check.go
> +func (c *Check) ServeHTTP(w http.ResponseWriter, r *http.Request) {
I cannot see the change.

2025-01-27 13:56 UTC, jroimartin commented on internal/http/check.go
> +}
Again. This has to change after the rewrite.

2025-01-27 13:56 UTC, jroimartin commented on internal/http/check.go
> +	mux := http.ServeMux{}
```suggestion
	mux := http.NewServeMux()
```

2025-01-27 13:56 UTC, jroimartin commented on internal/http/check.go
>  	c.Logger.Info("Shutdown: waiting for shuttedDown")
```suggestion
	c.Logger.Info("Shutdown: waiting for server shutdown")
```

2025-01-27 13:56 UTC, jroimartin commented on internal/http/check.go
> +	c.inShutdown.Store(true)
Now that you don't send a different response depending on the state of the server, I'd just remove the atomic.

2025-01-27 14:41 UTC, jesusfcr commented on .github/workflows/build.yaml
> +          go test -v -count 1 ./...
Done in79ab287f168b84ec65314e3027bd4c8df86693db

2025-01-27 16:27 UTC, jesusfcr commented on internal/http/check.go
> +func (c *Check) ServeHTTP(w http.ResponseWriter, r *http.Request) {
Ok, I missed, but not sure what name is ok.

2025-01-27 16:28 UTC, jesusfcr commented on internal/http/check.go
>  	c.Logger.Info("Shutdown: waiting for shuttedDown")
See 6f35590

2025-01-27 16:28 UTC, jesusfcr commented on internal/http/check.go
> +	c.inShutdown.Store(true)
See 6f35590

2025-01-27 16:29 UTC, jesusfcr commented on internal/http/check.go
> +	mux := http.ServeMux{}
See 6f35590

2025-01-27 16:30 UTC, jroimartin commented on internal/http/check.go
> +	c.inShutdown.Store(true)
I mean `inShutdown` all together.

2025-01-27 16:33 UTC, jesusfcr commented on config/config.go
> +				if len(s.Value) == 40 { // is the commin hash length
Ok, done in 537475f

2025-01-27 16:33 UTC, jesusfcr commented on config/config.go
> +}
done in 537475f

2025-01-27 16:33 UTC, jesusfcr commented on config/config.go
> +	c.VcsRevision = getVcsRevision()
right 537475f

2025-02-04 13:45 UTC, jroimartin commented
@jesusfcr I pushed cd5a706 to fix a deadlock on server shutdown. PTAL.

2025-02-06 11:13 UTC, jesusfcr commented on config/config.go
> +			if regexp.MustCompile(`[0-9a-f]{40}`).MatchString(s.Value) {
Ok, I didn't do that before because the regexp is likely executed just once.

2025-02-06 11:35 UTC, jroimartin submitted a review, later dismissed
LGTM

2025-02-06 12:37 UTC, seilagamo requested changes

2025-02-06 12:45 UTC, jesusfcr commented on .github/workflows/build.yaml
> +          go-version: '>=1.19'
Well, it is a >=, in fact, looking into the logs I see is using 1.23.5.

But for being consistent on the go.mod I think it's fair to add it. Thanks!

2025-02-06 12:56 UTC, seilagamo commented on config/config.go
> +	}
Never mind. I saw a thing that wasn't a thing.

2025-02-06 12:57 UTC, seilagamo approved these changes
LGTM

2025-02-12 15:42 UTC, merged